### ISSUE TITLE
Results does not look as good as the existing reconstruction.jpg

### ISSUE THREAD

**Issue by canlinzhang** [Horizon2333/imagenet-autoencoder#10]
Dear Author:

Thank you for your quick response in my last issue! I hope this letter finds you well ^_^

Another quick issue: I downloaded from the Model zoo vgg16, vgg19 and resnet152 trained checkpoints (.pth files). Then, I use `python tools/reconstruct.py --arch model-name --resume results/model-ckpt.pth --val_list caltech101_list.txt` to obtain the comparison results. But the obtained .jpg file does not look as good as the one you shared at the top of this repository. 

Say, this is the one obtained from vgg16:
![reconstruction_official_caltech256_vgg16](https://github.com/user-attachments/assets/0fb83bab-0815-49f2-afab-35052b9a052b)

You can see that the reconstructed image is obviously vague comparing to the original image. However, this is not the case in your shared result figs/reconstruction.jpg: I cannot see any difference between the reconstructed image and original image in that file.

Could you please tell me from which model you obtained that performance? Thanks!

**Comment by Horizon2333** [comment]
Thanks for your interest, my example image was not generated on Caltech101. This dataset is relatively small, so the trained model is not good. Similarly, you can refer to my previous example image, which are also blurry. The commit link is:
https://github.com/Horizon2333/imagenet-autoencoder/commit/927718d378bfafd9fdef5acd49bb895f014e6101
In addition, current image was generated on a large dataset and models trained on it. I forgot whether it was Objects365 or ImageNet.
