### ISSUE TITLE
License / Permission to use code

### ISSUE THREAD

**Issue by robertahunt** [Horizon2333/imagenet-autoencoder#2]
Hi Horizon2333,

I would like to use/build on this autoencoder for a project I am working on, but I don't see a license (MIT license, etc) for using this code. If I do make a paper, am I allowed to use your code / pretrained network. And if so, under what requirements? And how would you like it to be cited (just as a link to this page, for example?)

All the best,

Roberta

**Comment by Horizon2333** [comment]
Hi Roberta

I'm glad that my project can help you. Actually, I did these experiments out of my interest and I do not want to add any restrictions for using my code or pre-trained network. So you can feel free to do anything. And if you publish the code of your project, you can add a link to mine and that's enough.

Horizon2333
