### ISSUE TITLE
No resize in train_loader.

### ISSUE THREAD

**Issue by canlinzhang** [Horizon2333/imagenet-autoencoder#9]
Hi, thanks for the code!

I found that in dataloader.py, you defined
```
    val_trans = transforms.Compose([
                    transforms.Resize(256),                   
                    transforms.CenterCrop(224),
                    transforms.ToTensor()
                  ])
```
in the val_loader. 

However, in the train_loader, there is
```
    augmentation = [
        transforms.RandomResizedCrop(224, scale=(0.2, 1.)),
        #transforms.RandomGrayscale(p=0.2),
        #transforms.RandomApply([GaussianBlur([.1, 2.])], p=0.5),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
    ]
```

That says, the training process does not first resize the image to 256 * 256, whereas the validation process does. Is this a potential defect? Or do you by default assume all input images are 256 * 256? Thanks!

**Comment by Horizon2333** [comment]
Thank you for your interest. 
In fact, this operation is widely used in image tasks, that is, RandomCrop is used for data augmentation during the training phase and more complete images are retained for prediction during the testing phase. 
For example, the following are the ImageNet classification codes officially provided by Pytorch: (L239-255)
https://github.com/pytorch/examples/blob/main/imagenet/main.py
![image](https://github.com/user-attachments/assets/6bd7714d-2f3b-4276-a8cd-610565079ec3)

**Comment by canlinzhang** [comment]
Got it. Thanks!

**Comment by canlinzhang** [comment]
Thanks!
